[package]
name = "courier_caw"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
rayon = "*"
rand = "*"
chrono = "*"
rand_seeder = "*"
rand_pcg = "*"